import React from 'react'
import { TrendingUp, Users, Target, AlertTriangle, CheckCircle2 } from 'lucide-react'
import { analysisResults } from '../data/agentData'

function AnalysisPage() {
  const { vendorPerformance, statusDistribution, funnelMetrics, agentPerformance, compensationStatus, recommendations } = analysisResults

  return (
    <div className="space-y-6">
      {/* Page Header */}
      <div className="bg-white rounded-lg shadow p-6">
        <div className="bg-amber-50 border border-amber-200 rounded-lg p-3 mb-4">
          <p className="text-sm text-amber-800">
            <strong>Note:</strong> This analysis is based on data from Derrick's in-law's agency, not Derrick Bealer's Allstate Santa Barbara agency.
          </p>
        </div>
        <h2 className="text-xl font-semibold text-gray-900 mb-2">Analysis Results</h2>
        <p className="text-gray-600">
          Detailed analysis generated by the agent system from 54,332 lead records (in-law's agency).
        </p>
      </div>

      {/* Compensation Status */}
      <div className="bg-white rounded-lg shadow p-6">
        <div className="flex items-center mb-4">
          <Target className="w-5 h-5 text-purple-600 mr-2" />
          <h3 className="text-lg font-semibold text-gray-900">Compensation Status</h3>
        </div>

        <div className="grid md:grid-cols-2 gap-6">
          {/* PBR */}
          <div className="border rounded-lg p-4">
            <h4 className="text-sm font-semibold text-gray-700 mb-3">Policy Bundle Rate</h4>
            <div className="flex items-end justify-between mb-2">
              <div>
                <div className="text-3xl font-bold text-red-600">
                  {(compensationStatus.policyBundleRate.current * 100).toFixed(1)}%
                </div>
                <div className="text-sm text-gray-500">
                  Target: {(compensationStatus.policyBundleRate.target * 100).toFixed(0)}%
                </div>
              </div>
              <div className="text-right">
                <div className="text-sm text-red-600 font-medium">
                  Gap: {(compensationStatus.policyBundleRate.gap * 100).toFixed(1)}%
                </div>
                <div className="text-xs text-gray-500">
                  Next bonus at {(compensationStatus.policyBundleRate.nextBonusAt * 100).toFixed(0)}%
                </div>
              </div>
            </div>
            <div className="w-full bg-gray-200 rounded-full h-3">
              <div
                className="bg-red-500 h-3 rounded-full"
                style={{ width: `${(compensationStatus.policyBundleRate.current / 0.5) * 100}%` }}
              ></div>
            </div>
          </div>

          {/* PG */}
          <div className="border rounded-lg p-4">
            <h4 className="text-sm font-semibold text-gray-700 mb-3">Portfolio Growth</h4>
            <div className="flex items-end justify-between mb-2">
              <div>
                <div className="text-3xl font-bold text-red-600">
                  {compensationStatus.portfolioGrowth.currentItems}
                </div>
                <div className="text-sm text-gray-500">
                  {compensationStatus.portfolioGrowth.currentTier}
                </div>
              </div>
              <div className="text-right">
                <div className="text-sm text-orange-600 font-medium">
                  {compensationStatus.portfolioGrowth.itemsToNextTier} to {compensationStatus.portfolioGrowth.nextTier}
                </div>
                <div className="text-xs text-gray-500">
                  Payout: ${compensationStatus.portfolioGrowth.nextPayout}
                </div>
              </div>
            </div>
            <div className="w-full bg-gray-200 rounded-full h-3">
              <div
                className="bg-red-500 h-3 rounded-full"
                style={{ width: '5%' }}
              ></div>
            </div>
          </div>
        </div>
      </div>

      {/* Vendor Performance */}
      <div className="bg-white rounded-lg shadow p-6">
        <div className="flex items-center mb-4">
          <TrendingUp className="w-5 h-5 text-blue-600 mr-2" />
          <h3 className="text-lg font-semibold text-gray-900">Vendor Performance</h3>
        </div>

        <div className="overflow-x-auto">
          <table className="min-w-full">
            <thead>
              <tr className="bg-gray-50">
                <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase">Vendor</th>
                <th className="px-4 py-3 text-right text-xs font-medium text-gray-500 uppercase">Total Leads</th>
                <th className="px-4 py-3 text-right text-xs font-medium text-gray-500 uppercase">Quoted</th>
                <th className="px-4 py-3 text-right text-xs font-medium text-gray-500 uppercase">Quote Rate</th>
                <th className="px-4 py-3 text-right text-xs font-medium text-gray-500 uppercase">Avg Duration</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-gray-200">
              {Object.entries(vendorPerformance).map(([vendor, stats], index) => (
                <tr key={vendor} className={index === 0 ? "bg-green-50" : ""}>
                  <td className="px-4 py-3 text-sm font-medium text-gray-900">
                    {vendor}
                    {index === 0 && <span className="ml-2 text-xs text-green-600">Top</span>}
                  </td>
                  <td className="px-4 py-3 text-sm text-right text-gray-900">{stats.totalLeads.toLocaleString()}</td>
                  <td className="px-4 py-3 text-sm text-right text-gray-900">{stats.quoted}</td>
                  <td className="px-4 py-3 text-sm text-right">
                    <span className={`font-medium ${stats.quoteRate >= 0.02 ? 'text-green-600' : 'text-gray-600'}`}>
                      {(stats.quoteRate * 100).toFixed(1)}%
                    </span>
                  </td>
                  <td className="px-4 py-3 text-sm text-right text-gray-600">{stats.avgCallDuration.toFixed(1)}s</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>

      {/* Funnel Metrics */}
      <div className="bg-white rounded-lg shadow p-6">
        <h3 className="text-lg font-semibold text-gray-900 mb-4">Sales Funnel Analysis</h3>

        {/* Funnel Visual */}
        <div className="flex items-center justify-center mb-6">
          <div className="flex items-center space-x-2">
            <div className="text-center">
              <div className="w-32 h-16 bg-blue-100 rounded flex items-center justify-center">
                <span className="text-lg font-bold text-blue-700">{funnelMetrics.called.toLocaleString()}</span>
              </div>
              <div className="text-xs text-gray-500 mt-1">Called</div>
            </div>
            <div className="text-gray-400">→</div>
            <div className="text-center">
              <div className="w-28 h-14 bg-yellow-100 rounded flex items-center justify-center">
                <span className="text-lg font-bold text-yellow-700">{funnelMetrics.contacted.toLocaleString()}</span>
              </div>
              <div className="text-xs text-gray-500 mt-1">Contacted</div>
            </div>
            <div className="text-gray-400">→</div>
            <div className="text-center">
              <div className="w-24 h-12 bg-green-100 rounded flex items-center justify-center">
                <span className="text-lg font-bold text-green-700">{funnelMetrics.quoted.toLocaleString()}</span>
              </div>
              <div className="text-xs text-gray-500 mt-1">Quoted</div>
            </div>
            <div className="text-gray-400">→</div>
            <div className="text-center">
              <div className="w-20 h-10 bg-purple-100 rounded flex items-center justify-center">
                <span className="text-lg font-bold text-purple-700">{funnelMetrics.sold.toLocaleString()}</span>
              </div>
              <div className="text-xs text-gray-500 mt-1">Sold</div>
            </div>
          </div>
        </div>

        {/* Conversion Rates */}
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
          <div className="p-3 bg-gray-50 rounded-lg text-center">
            <div className="text-2xl font-bold text-gray-700">{(funnelMetrics.calledToContacted * 100).toFixed(1)}%</div>
            <div className="text-xs text-gray-500">Called → Contacted</div>
          </div>
          <div className="p-3 bg-gray-50 rounded-lg text-center">
            <div className="text-2xl font-bold text-gray-700">{(funnelMetrics.quotedToSold * 100).toFixed(1)}%</div>
            <div className="text-xs text-gray-500">Quoted → Sold</div>
          </div>
          <div className="p-3 bg-blue-50 rounded-lg text-center">
            <div className="text-2xl font-bold text-blue-700">{(funnelMetrics.overallConversion * 100).toFixed(1)}%</div>
            <div className="text-xs text-blue-600">Overall Conversion</div>
          </div>
          <div className="p-3 bg-green-50 rounded-lg text-center">
            <div className="text-2xl font-bold text-green-700">{funnelMetrics.sold}</div>
            <div className="text-xs text-green-600">Total Conversions</div>
          </div>
        </div>
      </div>

      {/* Agent Performance */}
      <div className="bg-white rounded-lg shadow p-6">
        <div className="flex items-center mb-4">
          <Users className="w-5 h-5 text-green-600 mr-2" />
          <h3 className="text-lg font-semibold text-gray-900">Agent Performance</h3>
        </div>

        <div className="overflow-x-auto">
          <table className="min-w-full">
            <thead>
              <tr className="bg-gray-50">
                <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase">Agent</th>
                <th className="px-4 py-3 text-right text-xs font-medium text-gray-500 uppercase">Total Calls</th>
                <th className="px-4 py-3 text-right text-xs font-medium text-gray-500 uppercase">Conversions</th>
                <th className="px-4 py-3 text-right text-xs font-medium text-gray-500 uppercase">Conv Rate</th>
                <th className="px-4 py-3 text-right text-xs font-medium text-gray-500 uppercase">Avg Duration</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-gray-200">
              {agentPerformance.map((agent, index) => (
                <tr key={agent.name} className={index === 0 ? "bg-green-50" : ""}>
                  <td className="px-4 py-3 text-sm font-medium text-gray-900">
                    {agent.name}
                    {index === 0 && <span className="ml-2 text-xs text-green-600">Top Performer</span>}
                  </td>
                  <td className="px-4 py-3 text-sm text-right text-gray-900">{agent.totalCalls.toLocaleString()}</td>
                  <td className="px-4 py-3 text-sm text-right text-gray-900">{agent.conversions}</td>
                  <td className="px-4 py-3 text-sm text-right">
                    <span className={`font-medium ${agent.conversionRate >= 0.025 ? 'text-green-600' : 'text-gray-600'}`}>
                      {(agent.conversionRate * 100).toFixed(1)}%
                    </span>
                  </td>
                  <td className="px-4 py-3 text-sm text-right text-gray-600">{agent.avgDuration.toFixed(1)}s</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>

      {/* Status Distribution */}
      <div className="bg-white rounded-lg shadow p-6">
        <h3 className="text-lg font-semibold text-gray-900 mb-4">Lead Status Distribution</h3>
        <div className="space-y-3">
          {Object.entries(statusDistribution).map(([status, count]) => {
            const total = Object.values(statusDistribution).reduce((a, b) => a + b, 0)
            const percentage = (count / total) * 100
            return (
              <div key={status}>
                <div className="flex justify-between text-sm mb-1">
                  <span className="text-gray-700">{status}</span>
                  <span className="text-gray-500">{count.toLocaleString()} ({percentage.toFixed(1)}%)</span>
                </div>
                <div className="w-full bg-gray-200 rounded-full h-2">
                  <div
                    className={`h-2 rounded-full ${
                      status.includes('SOLD') ? 'bg-green-500' :
                      status.includes('QUOTED') ? 'bg-blue-500' :
                      status.includes('CONTACTED') ? 'bg-yellow-500' :
                      'bg-gray-400'
                    }`}
                    style={{ width: `${percentage}%` }}
                  ></div>
                </div>
              </div>
            )
          })}
        </div>
      </div>

      {/* Recommendations */}
      <div className="bg-white rounded-lg shadow p-6">
        <div className="flex items-center mb-4">
          <AlertTriangle className="w-5 h-5 text-orange-600 mr-2" />
          <h3 className="text-lg font-semibold text-gray-900">Optimization Recommendations</h3>
        </div>

        <div className="space-y-4">
          {recommendations.map((rec, index) => (
            <div
              key={index}
              className={`p-4 rounded-lg border-l-4 ${
                rec.priority === 'high' ? 'border-red-500 bg-red-50' : 'border-yellow-500 bg-yellow-50'
              }`}
            >
              <div className="flex items-start justify-between">
                <div>
                  <div className="flex items-center">
                    <span className={`text-sm font-semibold ${
                      rec.priority === 'high' ? 'text-red-700' : 'text-yellow-700'
                    }`}>
                      {rec.area}
                    </span>
                    <span className={`ml-2 px-2 py-0.5 text-xs rounded ${
                      rec.priority === 'high' ? 'bg-red-200 text-red-800' : 'bg-yellow-200 text-yellow-800'
                    }`}>
                      {rec.priority}
                    </span>
                  </div>
                  <p className="text-sm text-gray-600 mt-1">{rec.issue}</p>
                  <p className="text-sm font-medium text-gray-800 mt-2">{rec.action}</p>
                </div>
                <div className="text-right">
                  <div className="text-xs text-gray-500">Impact</div>
                  <div className="text-sm text-green-600">{rec.impact}</div>
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  )
}

export default AnalysisPage
